# Generated by Django 4.2 on 2023-05-07 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Conversation',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('title', models.CharField(max_length=200)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('status', models.CharField(choices=[('active', 'Активная'), ('closed', 'Закрыта'), ('snoozed', 'Отложена')],
                                    default='Активный', max_length=20)),
        ('user1', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='conversations_started', to=settings.AUTH_USER_MODEL)),
        ('user2', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='conversations_involved', to=settings.AUTH_USER_MODEL)),
      ],
      options={
        'verbose_name': 'Диалог',
        'verbose_name_plural': 'Диалоги',
        'ordering': ['-created_at'],
        'unique_together': {('user1', 'user2')},
      },
    ),
    migrations.CreateModel(
      name='Message',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('text', models.TextField()),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                           to='messages_home.conversation')),
        ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                     to=settings.AUTH_USER_MODEL)),
      ],
      options={
        'verbose_name': 'Сообщение',
        'verbose_name_plural': 'Сообщения',
        'ordering': ('created_at',),
      },
    ),
    migrations.CreateModel(
      name='Attachment',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('file', models.FileField(upload_to='attachments/')),
        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
        ('message',
         models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='messages_home.message')),
        ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
      ],
      options={
        'verbose_name': 'Вложение',
        'verbose_name_plural': 'Вложения',
      },
    ),
  ]
