# Generated by Django 4.2 on 2023-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('messages_home', '0002_alter_conversation_user1_alter_conversation_user2'),
  ]

  operations = [
    migrations.AlterField(
      model_name='conversation',
      name='status',
      field=models.CharField(choices=[('active', 'Активная'), ('closed', 'Закрыта'), ('snoozed', 'Отложена')],
                             default='Активная', max_length=20),
    ),
  ]
