# Generated by Django 4.2 on 2023-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_home', '0003_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
