# Generated by Django 4.2 on 2023-05-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('messages_home', '0004_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='messages_home.attachment'),
        ),
    ]
